@Regies.API_HostAddress = https://localhost:7246
@Host = https://localhost
@port = 7246

@RegiesAPI_HostAddress = {{Host}}:{{port}}

GET {{Regies.API_HostAddress}}/api/regies

###

GET {{Regies.API_HostAddress}}/api/regies/2

###

POST {{Regies.API_HostAddress}}/api/regies/create
Content-Type: application/json

{
  "Nom" : "Immo.ch", 
  "estActive" : true,
  "contactEmail" : "emai@emailcom",
  "contactTelephone" :"6666",
  "City" : "Geneve",
  "Street" : "Rue de la paix",
   "StreetNumber" : "42",
  "ZipCode" : "5444"
}

###
