// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Regies.Infrastructure.Persistence;

#nullable disable

namespace Regies.Infrastructure.Migrations
{
    [DbContext(typeof(RegiesDBContext))]
    [Migration("20241015143514_BienImmoModifie")]
    partial class BienImmoModifie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Regies.Domain.Model.BienImmobilier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomAnnonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegieId")
                        .HasColumnType("int");

                    b.Property<int>("_typeBien")
                        .HasColumnType("int");

                    b.Property<int?>("anneeCOnstruction")
                        .HasColumnType("int");

                    b.Property<bool>("isLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("pourParticulier")
                        .HasColumnType("bit");

                    b.Property<decimal>("prixLocatif")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.Property<decimal>("prixVente")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RegieId");

                    b.ToTable("BienImmobiliers");
                });

            modelBuilder.Entity("Regies.Domain.Model.Regie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Regies");
                });

            modelBuilder.Entity("Regies.Domain.Model.BienImmobilier", b =>
                {
                    b.HasOne("Regies.Domain.Model.Regie", null)
                        .WithMany("lesBiensDeLaRegie")
                        .HasForeignKey("RegieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Regies.Domain.Model.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("BienImmobilierId")
                                .HasColumnType("int");

                            b1.Property<string>("Rue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ville")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("codePostal")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("numeroRue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BienImmobilierId");

                            b1.ToTable("BienImmobiliers");

                            b1.WithOwner()
                                .HasForeignKey("BienImmobilierId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });

            modelBuilder.Entity("Regies.Domain.Model.Regie", b =>
                {
                    b.OwnsOne("Regies.Domain.Model.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("RegieId")
                                .HasColumnType("int");

                            b1.Property<string>("Rue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ville")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("codePostal")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("numeroRue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RegieId");

                            b1.ToTable("Regies");

                            b1.WithOwner()
                                .HasForeignKey("RegieId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });

            modelBuilder.Entity("Regies.Domain.Model.Regie", b =>
                {
                    b.Navigation("lesBiensDeLaRegie");
                });
#pragma warning restore 612, 618
        }
    }
}
